### ISSUE TITLE
status 500 twitter connection

### ISSUE THREAD

**Issue by montao** [haystack/eyebrowse-server#160]
I got a status 500 when trying to connect my twitter account
http://eyebrowse.csail.mit.edu/accounts/profile/sync_twitter?oauth_token=ep3hLAAAAAAAeKUBAAABVyPPgqc&oauth_verifier=rcijnzJDHylTLYJ9v4mvdpYN84IPfBbK​

It's probably in the function sync_twitter in views.py

**Comment by joshblum** [comment]
traceback:

```
Traceback (most recent call last):

File "python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
  response = callback(request, *callback_args, **callback_kwargs)
File "python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
  return view_func(request, *args, **kwargs)
File "python2.7/site-packages/annoying/decorators.py", line 74, in wrapper
  output = function(request, *args, **kwargs)
File "/eyebrowse-server/accounts/views.py", line 293, in sync_twitter
  access_token=token, access_token_secret=secret)
File "python2.7/site-packages/django/db/models/manager.py", line 137, in create
  return self.get_query_set().create(**kwargs)
File "python2.7/site-packages/django/db/models/query.py", line 377, in create
  obj.save(force_insert=True, using=self.db)
File "python2.7/site-packages/django/db/models/base.py", line 463, in save
  self.save_base(using=using, force_insert=force_insert, force_update=force_update)
File "python2.7/site-packages/django/db/models/base.py", line 551, in save_base
  result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
File "python2.7/site-packages/django/db/models/manager.py", line 203, in _insert
  return insert_query(self.model, objs, fields, **kwargs)
File "python2.7/site-packages/django/db/models/query.py", line 1593, in insert_query
  return query.get_compiler(using=using).execute_sql(return_id)
File "python2.7/site-packages/django/db/models/sql/compiler.py", line 912, in execute_sql
  cursor.execute(sql, params)
File "python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 52, in execute
  return self.cursor.execute(query, args)
DatabaseError: integer out of range
```
