### ISSUE TITLE
can't blacklist right now because of bug related to setting a port value

### ISSUE THREAD

**Issue by amyxzhang** [haystack/eyebrowse-server#83]
Traceback (most recent call last):

File "/eyebrowse-virtualenv/lib/python2.7/site-packages/tastypie/resources.py", line 192, in wrapper
  response = callback(request, *args, **kwargs)
File "/eyebrowse-virtualenv/lib/python2.7/site-packages/tastypie/resources.py", line 397, in dispatch_list
  return self.dispatch('list', request, **kwargs)
File "/eyebrowse-virtualenv/lib/python2.7/site-packages/tastypie/resources.py", line 427, in dispatch
  response = method(request, **kwargs)
File "/eyebrowse-virtualenv/lib/python2.7/site-packages/tastypie/resources.py", line 1165, in post_list
  updated_bundle = self.obj_create(bundle, request=request, **self.remove_api_resource_names(kwargs))
File "/eyebrowse-server/api/resources.py", line 212, in obj_create
  bundle, request, user=request.user, **kwargs)
File "/eyebrowse-virtualenv/lib/python2.7/site-packages/tastypie/resources.py", line 1780, in obj_create
  bundle.obj.save()
File "/eyebrowse-virtualenv/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
  self.save_base(using=using, force_insert=force_insert, force_update=force_update)
File "/eyebrowse-virtualenv/lib/python2.7/site-packages/django/db/models/base.py", line 551, in save_base
  result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
File "/eyebrowse-virtualenv/lib/python2.7/site-packages/django/db/models/manager.py", line 203, in _insert
  return insert_query(self.model, objs, fields, **kwargs)
File "/eyebrowse-virtualenv/lib/python2.7/site-packages/django/db/models/query.py", line 1593, in insert_query
  return query.get_compiler(using=using).execute_sql(return_id)
File "/eyebrowse-virtualenv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 911, in execute_sql
  for sql, params in self.as_sql():
File "/eyebrowse-virtualenv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 872, in as_sql
  for obj in self.query.objs
File "/eyebrowse-virtualenv/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 292, in get_db_prep_save
  prepared=False)
File "/eyebrowse-virtualenv/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 284, in get_db_prep_value
  value = self.get_prep_value(value)
File "/eyebrowse-virtualenv/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
  return int(value)
ValueError: invalid literal for int() with base 10: ''

WSGIRequest path:/api/v1/blacklist, GET:QueryDict: {}, POST:QueryDict: {u'{"url":"www.facebook.com","port":"","user":"/api/v1/user/amyxzhang/"}': [u'']}, COOKIES:{'SESS8e2fec643916a8cd9434aaec6daf04c7': ‘haluoighcgm9tmvjarjvsqqdv0’,

**Comment by joshblum** [comment]
@amyxzhang i was able to create locally after 18fc5f695b7ebb69fbc2d065755c05000c4fa4d8, do you still see the issue?

**Comment by amyxzhang** [comment]
looks good!
